"""Request/response contract surface for the v1 API."""

from app.schemas.common import (
    BoundingBox,
    Detection,
    ErrorResponse,
    HealthResponse,
    LatencyBreakdown,
    MessageResponse,
    ORMModel,
    Page,
    PageMeta,
)
from app.schemas.expiry import (
    ExpiryAuditRead,
    ExpiryExtraction,
    ExpiryExtractRequest,
    ExpiryExtractResponse,
    ExpirySummary,
)
from app.schemas.freshness import (
    FreshnessAuditRead,
    FreshnessClassifyRequest,
    FreshnessClassifyResponse,
    FreshnessPrediction,
    FreshnessSummary,
)
from app.schemas.insights import (
    InsightAction,
    InsightRequest,
    InsightResponse,
    OllamaStatus,
)
from app.schemas.inventory import (
    DiscrepancyItem,
    InventoryLogRead,
    InventoryScanRequest,
    InventoryScanResponse,
    InventorySummary,
)
from app.schemas.planogram import (
    ComplianceAuditRead,
    ComplianceCheckRequest,
    ComplianceCheckResponse,
    PlanogramCreate,
    PlanogramDetail,
    PlanogramDocument,
    PlanogramRead,
    PlanogramRow,
    PlanogramShelf,
    PlanogramSlot,
    PlanogramTolerances,
    SlotResult,
)
from app.schemas.product import ProductCreate, ProductRead, ProductUpdate

__all__ = [
    "BoundingBox",
    "ComplianceAuditRead",
    "ComplianceCheckRequest",
    "ComplianceCheckResponse",
    "Detection",
    "DiscrepancyItem",
    "ErrorResponse",
    "ExpiryAuditRead",
    "ExpiryExtractRequest",
    "ExpiryExtractResponse",
    "ExpiryExtraction",
    "ExpirySummary",
    "FreshnessAuditRead",
    "FreshnessClassifyRequest",
    "FreshnessClassifyResponse",
    "FreshnessPrediction",
    "FreshnessSummary",
    "HealthResponse",
    "InsightAction",
    "InsightRequest",
    "InsightResponse",
    "InventoryLogRead",
    "InventoryScanRequest",
    "InventoryScanResponse",
    "InventorySummary",
    "LatencyBreakdown",
    "MessageResponse",
    "ORMModel",
    "OllamaStatus",
    "Page",
    "PageMeta",
    "PlanogramCreate",
    "PlanogramDetail",
    "PlanogramDocument",
    "PlanogramRead",
    "PlanogramRow",
    "PlanogramShelf",
    "PlanogramSlot",
    "PlanogramTolerances",
    "ProductCreate",
    "ProductRead",
    "ProductUpdate",
    "SlotResult",
]
